apiVersion: v2
name: blocky
description: A Helm chart for Blocky DNS Server - Fast and lightweight DNS proxy with ad-blocking
type: application
version: 1.0.2
appVersion: "latest"
keywords:
  - dns
  - adblock
  - privacy
  - blocky
  - dns-proxy
maintainers:
  - name: Levent Yalcin
    url: https://github.com/leventyalcin
home: https://0xerr0r.github.io/blocky/
sources:
  - https://github.com/0xERR0R/blocky
