{{- if .Values.webService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blocky.fullname" . }}-http
  labels:
    {{- include "blocky.labels" . | nindent 4 }}
    app.kubernetes.io/component: http
  {{- with .Values.webService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.webService.type }}
  ports:
    - name: http
      port: {{ .Values.webService.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "blocky.selectorLabels" . | nindent 4 }}
{{- end }}
